services:
  cplit:
    build: .
    expose:
      - "3000"
    volumes:
      - ./cplit.config.yaml:/app/cplit.config.yaml:ro
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - npass

networks:
  npass:
    external: true
